events {
    worker_connections 1024;
}
http {
    sendfile	on;
    keepalive_timeout  65;
    # resolver <dns_addr>; # required if apprise API is a domain name
    lua_package_path "/usr/local/openresty/lualib/?.lua;/usr/local/lua/openresty-Dynamic-Access-Control/?.lua;/usr/local/lua/openresty-Dynamic-Access-Control/access_functions/?.lua;/usr/local/lua/openresty-Dynamic-Access-Control/general_functions/?.lua;;";
    lua_code_cache on;
    error_log /var/log/nginx/error.log debug;
    lua_shared_dict ip_blacklist_cache 10m;
    lua_shared_dict ip_whitelist_cache 10m;
    lua_shared_dict prometheus_metrics 10m;
    init_worker_by_lua_file /usr/local/lua/openresty-Dynamic-Access-Control/init_functions/worker_init.lua;
    log_by_lua_file /usr/local/lua/openresty-Dynamic-Access-Control/log.lua;
    server {
        listen 80;
        location / {
            access_by_lua_file /usr/local/lua/openresty-Dynamic-Access-Control/main.lua;
            root /usr/local/openresty/nginx/html;
            index index.html index.htm;
        }
    }
    server {
        listen 9145;
        location /metrics {
            content_by_lua_file /usr/local/lua/openresty-Dynamic-Access-Control/metrics_content.lua;
        }
    }
    #this is for tests, should be dissabled or removed in prod
    server {
        listen 4956;
        location / {
            content_by_lua_block {
                local bl = ngx.shared.ip_blacklist_cache
                local wt = ngx.shared.ip_whitelist_cache
                bl:flush_all()
                wt:flush_all()
                ngx.say(wt:get_keys(0))
                ngx.say(bl:get_keys(0))
            }
        }
    }
}
